name: java-keytool-steps
version: 1.1.0
rundeckPluginVersion: 1.2
author: alexh and csinks
date: Mon Sep 10 2018
providers:
  - name: java-keytool-list-step
    service: RemoteScriptNodeStep
    title: 'java / keytool / list'
    description: 'Run keytool list action.'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: keytoolw
    script-args: --action list --jdk-home ${config.jdk_home} --keystore-path ${config.keystore_path}
    config:
      - type: String
        name: keystore_path
        title: Keystore Path*
        description: 'Path to the jdk keystore'
        required: true        
      - type: String
        name: keystore_password
        title: Keystore Password*
        description: 'Path to keystore password'
        required: true
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: jdk_home
        title: JDK Home
        description: 'Path to the jdk. If left blank, will search for the jdk in $PATH.'
      - type: String
        name: alias
        title: Alias
        description: 'Alias name. If left blank, will list all certificates in the keystore.' 
  - name: java-keytool-printcert-step
    service: RemoteScriptNodeStep
    title: 'java / keytool / printcert'
    description: 'Run keytool printcert action.'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: keytoolw
    script-args: --action printcert --jdk-home ${config.jdk_home} --cert-path ${config.cert_path}
    config:
      - type: String
        name: cert_path
        title: Certificate Path*
        description: 'Path to the jdk keystore'
        required: true
      - type: String
        name: jdk_home
        title: JDK Home
        description: 'Path to the jdk. If left blank, will search for the jdk in $PATH'
  - name: java-keytool-checkExp-step
    service: RemoteScriptNodeStep
    title: 'java / keytool / checkExpiration'
    description: 'Check certificate expiration date.'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: keytoolw
    script-args: --action checkExp --jdk-home ${config.jdk_home} --keystore-path ${config.keystore_path} --age-thresh ${config.age_thresh}
    config:
      - type: String
        name: keystore_path
        title: Keystore Path*
        description: 'Path to the jdk keystore'
        required: true        
      - type: String
        name: keystore_password
        title: Keystore Password*
        description: 'Path to keystore password'
        required: true
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: alias
        title: Alias*
        description: 'Alias name' 
        required: true
      - type: Integer
        name: age_thresh
        title: Age Threshhold (days)
        description: 'If specified, fail the job if the certificate expires in this many days or less'
      - type: String
        name: jdk_home
        title: JDK Home
        description: 'Path to the jdk. If left blank, will search for the jdk in $PATH.'
  - name: java-keytool-create-step
    service: RemoteScriptNodeStep
    title: 'java / keytool / create'
    description: 'Create a new keystore and/or key pair and optionally generate a certificate request'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: keytoolw
    script-args: --action create --jdk-home ${config.jdk_home} --keystore-path ${config.keystore_path} --overwrite-keystore ${config.overwrite_keystore} 
    config:
      - type: String
        name: keystore_path
        title: Keystore Path*
        description: 'Path to the jdk keystore'
        required: true        
      - type: Boolean
        name: overwrite_keystore
        title: 'Overwrite keystore?'
        description: 'Overwrite keystore if it exists? If unchecked, will attempt to add alias to existing keystore.'
      - type: String
        name: keystore_password
        title: Keystore Password*
        description: 'Path to keystore password'
        required: true
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: private_key_password
        title: Private Key Password*
        description: 'Path to private key password'
        required: true
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: alias
        title: Alias*
        description: 'Alias name' 
        required: true
      - type: String
        name: key_alg
        title: Key Algorithm [RSA]
        description: Keypair Algorithm 
        required: true        
        default: "RSA"
      - type: Integer
        name: key_size
        title: Key Size [2048]
        description: Key Size
        required: true        
        default: 2048
      - type: String
        name: common_name
        title: Common Name (CN)*
        description: Common Name
        required: true
      - type: String
        name: org_unit 
        title: Organization Unit (OU)*
        description: Organization Unit
        required: true
      - type: String
        name: org_name 
        title: Organization Name (O)*
        description: Organization Name
        required: true
      - type: String
        name: loc_name 
        title: Locality Name (L)*
        description: Locality Name
        required: true
      - type: String
        name: state_name 
        title: State Name (ST)*
        description: State Name
        required: true
      - type: String
        name: country 
        title: Country (C)*
        description: Country
        required: true
      - type: Integer
        name: validity_period
        title: Validity Period (days) [365]
        description: Validity Period
        required: true        
        default: 365
      - type: String
        name: san
        title: Subject Alternative Name (Optional)
        description: "Comma-separated list of SANs. Ex: dns:hostname.domain.com,dns:hostalias.domain.com,ip:1.1.1.1"
      - type: String
        name: key_usage
        title: Key Usage (Optional)
        description: "Comma-separated list of valid Key Usages. Ex: digitalSignature,keyEncipherment,keyCertSign"
      - type: String
        name: jdk_home
        title: JDK Home
        description: 'Path to the jdk. If left blank, will search for the jdk in $PATH.'
      - type: String
        name: certreq_path
        title: Directory to create Certificate Request in
        description: "If specified, generate a certficicate request and save the certreq to the location specified."
  - name: java-keytool-import-step
    service: RemoteScriptNodeStep
    title: 'java / keytool / import'
    description: 'Import a root, intermediate, and/or a signed server certificate into an existing keystore'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: keytoolw
    script-args: --action import --jdk-home ${config.jdk_home} --keystore-path ${config.keystore_path} --cert-path ${config.cert_path}
    config:
      - type: String
        name: keystore_path
        title: Keystore Path*
        description: 'Path to the jdk keystore'
        required: true        
      - type: String
        name: keystore_password
        title: Keystore Password*
        description: 'Path to keystore password'
        required: true
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: private_key_password
        title: Private Key Password*
        description: 'Path to private key password for private key entry, if applicable. If not, enter "None"'
        required: true
        default: "None"
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: alias
        title: Alias*
        description: 'Certificate alias'
        required: true
      - type: String
        name: cert_path
        title: Server Certificate Path*
        description: 'Path to the certificate.'
        required: true
      - type: String
        name: jdk_home
        title: JDK Home
        description: 'Path to the jdk. If left blank, will search for the jdk in $PATH.'
  - name: java-keytool-delete-step
    service: RemoteScriptNodeStep
    title: 'java / keytool / delete'
    description: 'Delete an alias from a keystore.'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: keytoolw
    script-args: --action delete --jdk-home ${config.jdk_home} --keystore-path ${config.keystore_path}
    config:
      - type: String
        name: keystore_path
        title: Keystore Path*
        description: 'Path to the jdk keystore'
        required: true        
      - type: String
        name: keystore_password
        title: Keystore Password*
        description: 'Path to keystore password'
        required: true
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: alias
        title: Alias
        description: 'Alias name to delete' 
        required: true
      - type: String
        name: jdk_home
        title: JDK Home
        description: 'Path to the jdk. If left blank, will search for the jdk in $PATH.'
