name: java-keytool-steps
version: 1.0.0
rundeckPluginVersion: 1.2
author: alexh
date: Tue Feb 16 2016
providers:
  - name: java-keytool-list-step
    service: RemoteScriptNodeStep
    title: 'java / keytool / list'
    description: 'Run keytool list action.'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: keytoolw
    script-args: --action list --jdk-home ${config.jdk_home} --keystore-path ${config.keystore_path}
    config:
      - type: String
        name: keystore_path
        title: Keystore Path*
        description: 'Path to the jdk keystore'
        required: true        
      - type: String
        name: keystore_password
        title: Keystore Password*
        description: 'Path to keystore password'
        required: true
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: jdk_home
        title: JDK Home
        description: 'Path to the jdk. If left blank, will search for the jdk in $PATH.'
      - type: String
        name: alias
        title: Alias
        description: 'Alias name. If left blank, will list all certificates in the keystore.' 
  - name: java-keytool-printcert-step
    service: RemoteScriptNodeStep
    title: 'java / keytool / printcert'
    description: 'Run keytool printcert action.'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: keytoolw
    script-args: --action printcert --jdk-home ${config.jdk_home} --cert-path ${config.cert_path}
    config:
      - type: String
        name: cert_path
        title: Certificate Path*
        description: 'Path to the jdk keystore'
        required: true
      - type: String
        name: jdk_home
        title: JDK Home
        description: 'Path to the jdk. If left blank, will search for the jdk in $PATH'
  - name: java-keytool-checkExp-step
    service: RemoteScriptNodeStep
    title: 'java / keytool / checkExpiration'
    description: 'Check certificate expiration date.'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: keytoolw
    script-args: --action checkExp --jdk-home ${config.jdk_home} --keystore-path ${config.keystore_path} --age-thresh ${config.age_thresh}
    config:
      - type: String
        name: keystore_path
        title: Keystore Path*
        description: 'Path to the jdk keystore'
        required: true        
      - type: String
        name: keystore_password
        title: Keystore Password*
        description: 'Path to keystore password'
        required: true
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: alias
        title: Alias*
        description: 'Alias name' 
        required: true
      - type: Integer
        name: age_thresh
        title: Age Threshhold (days)
        description: 'If specified, fail the job if the certificate expires in this many days or less'
      - type: String
        name: jdk_home
        title: JDK Home
        description: 'Path to the jdk. If left blank, will search for the jdk in $PATH.'